# Generated by Django 4.2.16 on 2024-10-26 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
